language: python


git:
  depth: 99999


matrix:
  include:
    # - python: 3.3
    # - python: 3.4
    # - python: 3.5
    # - python: 3.6
    - python: 3.4.1

env:
  - APP_CONFIG_NAME=test


install:
 - pip install -r requirements.txt
 - pip install codecov
 - pip install pytest-cov


before_script:
 - "export PYTHONPATH=."

script:
  - flake8 middleware/ --ignore=F403,F405
  - python -m pytest --cov=./


after_success:
  - codecov


before_deploy:
- echo 'start deploying!'

deploy:
  - provider: azure_web_apps
    verbose: true
    skip_cleanup: true
    on: master
    slot: science-gateway-middleware
  - provider: azure_web_apps
    verbose: true
    skip_cleanup: true
    on: develop
    slot: science-gateway-middleware-dev
  - provider: azure_web_apps
    verbose: true
    skip_cleanup: true
    on: staging
    slot: science-gateway-middleware-staging

after_deploy: echo 'done deploying!'


notifications:
  slack:
    on_success: change
    on_failure: change
    rooms:
      - secure: BZLpMK+Hoh7Bv6CUqYvyebuxQiSi9KptXeCabjFBeJWPi7aLq09RNUI3w8QEsbnl2qmaLckDyaJBXLUvB1cb49Hp/q3obEh9wGBP5Y/Qbsi18pwHAFvJcZKAHVaTcNBBomvO4bYwopcZSmwiKzMdlk2BeYjbnPbf4DVo1QvGXqREw8R71Lk1oBgZ+KoienFkhdpG2pSECQV0iU6v+MbmwYBxV9k2B9bmySinxvvzwbV9nON/5dOYggPc6uIVCLbwaU3Y2c9ffzsXKGB/FrfYaWeYVRiZ3Gp2E6ZcAmK2AcjAfyij1IalU9D6AWBuKhHHxk+nJhyGK3tgvXlO1G3XTUBLhYgURvzTugLBJm0MU2KkTiSLxJEaZl+fUvoDuXmwwusZV8vZFHvwkdOBgnWFFcoH7ocy8OCfXFkFMDtpx+CwXFa/uBjLRhWmgwBXeIytHcfwHKVhgH7Vj7ShldgonTM0hcVoRldenXg22pK2W8MDcek16I9JZ6htJ/8f7doqOTNnepDIFHTBkpR3WQWd7GfdHwmxwwyJi5tJr3qpnkFAKaJhUAyNIPU5EU2JZTqGsxaYwLSI8xxIwMgzZTXijWIi5KXbsn85n1rpT9CsObLbROeYLngs9YvdarT6OvFIXSN9Oo05fW32iwvWuck001w8jn2pYD8u7jy5AMM1g4k=
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}. %{message}"
